# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target '29.Demo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'IQKeyboardManagerSwift'

  target '29.DemoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target '29.DemoUITests' do
    # Pods for testing
  end

end
