# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target '37.FirebasePushNotification' do
  use_frameworks!
  pod 'Firebase/Analytics'
  pod 'Firebase/Messaging'
end
