-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQg3xe/jEX+hniCXzCW
esJSTB1HUil0VtfH1+rm+BkmQBGgCgYIKoZIzj0DAQehRANCAARlzudNy39+Ocqz
D43pvMjrm5vMi/pHvSYZsq6cYMM+VfPZhg0TCk2G+gw5Am8tZ+aoHJ3PJw4IPbiz
s3DCLpk9
-----END PRIVATE KEY-----