# platform :ios, '14.0'

target 'MovieBox' do
  use_frameworks!
  pod 'Alamofire', '~> 5.4.3'
  pod 'SDWebImage', '~> 5.11.1'
  pod 'PullToRefreshKit', '~> 0.8.8'
  pod 'SVProgressHUD', '~> 2.2.5'
end

target 'MovieBoxTests' do
  use_frameworks!
  pod 'Alamofire', '~> 5.4.3'
  pod 'Mocker', '~> 2.5.2'
end
