# Uncomment the next line to define a global platform for your project
platform :ios, '11.0'

target 'DemoBitrise1' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Hmlet
  pod 'IQKeyboardManagerSwift'
  pod 'Alamofire'
  pod 'SDWebImage'
  pod 'Firebase/Core'
  pod 'Firebase/Messaging'
  pod 'Fabric', '~> 1.9.0'
  pod 'Crashlytics', '~> 3.12.0'
  pod 'SendBirdSDK'
  pod 'lottie-ios'
  
end
